quarkus.http.port=8082

quarkus.live-reload.instrumentation=true

quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=postgres
quarkus.datasource.password=029051
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/econolyze

banco-central-api/mp-rest/url=https://api.bcb.gov.br
banco-central-api/mp-rest/scope=jakarta.enterprise.context.ApplicationScoped
banco-central-api/mp-rest/connectTimeout=5000
banco-central-api/mp-rest/readTimeout=10000

quarkus.http.http2=true




# ou, se usa migrations, evite rodá-las nos testes quando não precisar
# quarkus.flyway.enabled=false

# Desabilitar JWT nos testes
quarkus.smallrye-jwt.enabled=false