quarkus.http.port=8082

quarkus.live-reload.instrumentation=true

quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=postgres
quarkus.datasource.password=029051
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/econolyze

banco-central-api/mp-rest/url=https://api.bcb.gov.br
banco-central-api/mp-rest/scope=jakarta.enterprise.context.ApplicationScoped
banco-central-api/mp-rest/connectTimeout=5000
banco-central-api/mp-rest/readTimeout=10000

quarkus.http.http2=true


quarkus.scheduler.enabled=true
quarkus.scheduler.timezone=America/Sao_Paulo

# ou, se usa migrations, evite rodá-las nos testes quando não precisar
# quarkus.flyway.enabled=false

# Habilita a autenticação via JWT
quarkus.smallrye-jwt.enabled=true

# Define quem emite o token (precisa bater com o campo "iss" do teu JWT)
mp.jwt.verify.issuer=econolyze

# Caminho pra chave pública usada pra verificar o token
mp.jwt.verify.publickey.location=keys/publicKey.pem
