quarkus.http.port=8082

# Testes: banco em memória
quarkus.datasource.db-kind=h2
quarkus.datasource.jdbc.url=jdbc:h2:mem:userDB
quarkus.hibernate-orm.database.generation=drop-and-create

# ou, se usa migrations, evite rodá-las nos testes quando não precisar
# quarkus.flyway.enabled=false

# Desabilitar JWT nos testes
quarkus.smallrye-jwt.enabled=false