quarkus.http.port=8081

# Database
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=${DB_USERNAME}
quarkus.datasource.password=${DB_PASSWORD}
quarkus.datasource.jdbc.url=${DB_URL}

# Permissões públicas
quarkus.http.auth.permission.public.paths=/auth/register,/auth/login,/auth/refresh,/auth/ping
quarkus.http.auth.permission.public.policy=permit

# Logging
quarkus.log.console.enable=true
quarkus.log.console.level=INFO
quarkus.log.level=INFO

# CORS
quarkus.http.cors.headers=accept,authorization,content-type,x-requested-with
quarkus.http.cors.methods=GET,POST,PUT,DELETE,OPTIONS

# JWT Configuration
mp.jwt.verify.publickey.location=publicKey.pem
app.jwt.issuer=econolyze
app.jwt.access-token-expiry=3600
app.jwt.refresh-token-expiry=86400
smallrye.jwt.sign.key.location=privateKey.pem
smallrye.jwt.new-token.issuer=econolyze
smallrye.jwt.new-token.lifespan=3600