quarkus.http.port=8081

quarkus.datasource.db-kind=h2
quarkus.datasource.jdbc.url=jdbc:h2:mem:userDB

quarkus.hibernate-orm.database.generation=drop-and-create


# JWT Token Issuer (iss)
smallrye.jwt.new-token.issuer=http://localhost

# JWT Token lifespan in seconds
smallrye.jwt.new-token.lifespan=3600

# JWT RS256 Signing key
smallrye.jwt.sign.key.location=testKey.pem

#mp.jwt.verify.publickey.location=publicVerificationKey.pem
#quarkus.native.resources.includes=publicVerificationKey.pem
#
#mp.jwt.verify.issuer=http://localhost
#
#smallrye.jwt.sign.key.location=privateSigningKey.pem