quarkus.http.port=8081

#mp.jwt.verify.publickey.location=publicVerificationKey.pem
#quarkus.native.resources.includes=publicVerificationKey.pem
#
#mp.jwt.verify.issuer=http://localhost
#
#smallrye.jwt.sign.key.location=privateSigningKey.pem