quarkus.langchain4j.timeout=60s

quarkus.langchain4j.ai.gemini.api-key=${GEMINI_API_KEY}
#quarkus.langchain4j.ai.gemini.chat-model.model-id=gemini-3-flash-preview
quarkus.langchain4j.ai.gemini.chat-model.model-id=gemini-3.1-flash-lite-preview
quarkus.langchain4j.ai.gemini.embedding-model.model-id=gemini-embedding-001
quarkus.langchain4j.ai.gemini.embedding-model.output-dimension=768
quarkus.langchain4j.ai.gemini.embedding-model.timeout=60s

quarkus.datasource.devservices.enabled=false
quarkus.langchain4j.devservices.enabled=false

quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=${DB_USERNAME}
quarkus.datasource.password=${DB_PASSWORD}

quarkus.datasource.reactive.url=${DB_URL}
quarkus.datasource.reactive.max-size=20

# quarkus.datasource.jdbc.additional-jdbc-properties.currentSchema=ai,public

quarkus.hibernate-orm.database.default-schema=ai

embedding.store.host=${DB_HOST}
embedding.store.port=${DB_PORT}
embedding.store.database=${DB_NAME}
embedding.store.user=${DB_USERNAME}
embedding.store.password=${DB_PASSWORD}

internal.secret=${INTERNAL_SECRET}

quarkus.rest-client.financial-service.url=http://localhost:8082
quarkus.rest-client.financial-service.scope=jakarta.inject.Singleton

quarkus.http.port=8083

mp.jwt.verify.publickey.location=keys/publicKey.pem
mp.jwt.verify.issuer=econolyze