quarkus.langchain4j.timeout=60s

# =========================
# CHAT - GROQ via OpenAI-compatible API
# =========================
quarkus.langchain4j.openai.api-key=${GROQ_API_KEY}
quarkus.langchain4j.openai.base-url=https://api.groq.com/openai/v1
quarkus.langchain4j.openai.chat-model.model-name=llama-3.3-70b-versatile
quarkus.langchain4j.openai.chat-model.temperature=0.3
quarkus.langchain4j.openai.chat-model.timeout=60s

quarkus.langchain4j.openai.embedding-model.enabled=false
quarkus.langchain4j.openai.moderation-model.enabled=false
quarkus.langchain4j.openai.image-model.enabled=false
quarkus.langchain4j.openai.chat-model.log-requests=true
quarkus.langchain4j.openai.chat-model.log-responses=true
# =========================
# EMBEDDING - GEMINI
# =========================
quarkus.langchain4j.ai.gemini.api-key=${GEMINI_API_KEY}
quarkus.langchain4j.ai.gemini.embedding-model.model-id=gemini-embedding-001
quarkus.langchain4j.ai.gemini.embedding-model.output-dimension=768
quarkus.langchain4j.ai.gemini.embedding-model.timeout=60s

# Se não quiser usar o chat do Gemini, deixa desligado
quarkus.langchain4j.ai.gemini.chat-model.enabled=false

quarkus.datasource.devservices.enabled=false
quarkus.langchain4j.devservices.enabled=false

quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=${DB_USERNAME}
quarkus.datasource.password=${DB_PASSWORD}

quarkus.datasource.jdbc.additional-jdbc-properties.sslmode=require
quarkus.datasource.jdbc.additional-jdbc-properties.prepareThreshold=0
quarkus.datasource.jdbc.additional-jdbc-properties.preferQueryMode=simple

quarkus.datasource.jdbc.max-size=5
quarkus.datasource.jdbc.min-size=1

quarkus.datasource.reactive.url=${DB_URL}
quarkus.datasource.jdbc.url=${DB_JDBC_URL}
quarkus.flyway.schemas=ai
quarkus.flyway.default-schema=ai
quarkus.flyway.table=flyway_schema_history
quarkus.datasource.reactive.max-size=20
quarkus.flyway.repair-at-start=true

quarkus.datasource.jdbc.additional-jdbc-properties.currentSchema=ai,public

quarkus.hibernate-orm.database.default-schema=ai

embedding.store.host=${DB_HOST}
embedding.store.port=${DB_PORT}
embedding.store.database=${DB_NAME}
embedding.store.user=${DB_USERNAME}
embedding.store.password=${DB_PASSWORD}

internal.secret=${INTERNAL_SECRET}

quarkus.rest-client.financial-service.url=http://financial-service:8082
quarkus.rest-client.financial-service.scope=jakarta.inject.Singleton

quarkus.http.port=8083

quarkus.flyway.migrate-at-start=true

mp.jwt.verify.publickey.location=keys/publicKey.pem
mp.jwt.verify.issuer=econolyze