mp.jwt.verify.publickey.location=keys/publicKey.pem
mp.jwt.verify.issuer=econolyze

quarkus.log.level=TRACE
quarkus.log.category."io.quarkus.smallrye.jwt".level=TRACE
quarkus.log.category."io.quarkus.security".level=TRACE
quarkus.log.category."io.smallrye.jwt".level=TRACE
