name: Deploy Back-End (Quarkus Native)

on:
  push:
    branches: [ "main" ]
    paths:
      - 'services/**'
  workflow_dispatch:

env:
  REGISTRY: ghcr.io

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    strategy:
      fail-fast: false 
      matrix:
        service: [auth-service, gateway-service, financial-service, ai-service]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21 (GraalVM)
        uses: actions/setup-java@v4 
        with:
          java-version: '21'
          distribution: 'graalvm'
          cache: 'maven'

      - name: Log in to the Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Native Image with Maven
        run: |
          cd services/${{ matrix.service }}
          chmod +x mvnw
          
          # Baixamos para 3g para garantir que não vai estourar os 7GB do GitHub
          ./mvnw package -Dnative -Dquarkus.native.native-image-xmx=3g -DskipTests
          
          # Lista os arquivos gerados para debug caso o Docker falhe de novo
          echo "==== CONTEÚDO DA PASTA TARGET ===="
          ls -lh target/

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: ./services/${{ matrix.service }}
          file: ./services/${{ matrix.service }}/src/main/docker/Dockerfile.native
          push: true
          tags: |
            ghcr.io/erickkamii/${{ matrix.service }}:latest

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Copy compose.yaml to Server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "services/compose.yaml"
          target: "/opt/econolyze"
          strip_components: 1

      - name: Executing remote ssh commands to deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /opt/econolyze
            echo "${{ secrets.GITHUB_TOKEN }}" | podman login ghcr.io -u ${{ github.actor }} --password-stdin
            podman compose pull
            podman compose up -d
            podman image prune -f